export { CreateNotePage } from "./CreateNotePage";
export { DealPage } from "./DealPage";
export { HomePage } from "./HomePage";
export { ActivityPage } from "./ActivityPage";
export { CreateContactPage } from "./CreateContactPage";
export { CreateDealPage } from "./CreateDealPage";
export { LinkPage } from "./LinkPage";
export { Main } from "./Main";
export { UpdateContactPage } from "./UpdateContactPage";
export { UpdateDealPage } from "./UpdateDealPage";
export { CreateActivityPage } from "./CreateActivityPage";
export * from "./admin";
